// <auto-generated />
using DataTravelManagement.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataTravelManagement.Migrations
{
    [DbContext(typeof(RollMasterContext))]
    [Migration("20251126053251_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataTravelManagement.Model.RollMaster", b =>
                {
                    b.Property<int>("RollID")
                        .HasColumnType("int");

                    b.Property<string>("RollName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RollID");

                    b.ToTable("TMS_RollMaster", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
